### ISSUE TITLE
Inherit the image extension from the original image

### ISSUE THREAD

**Issue by yasharora102** [yasharora102/image-colorization-api#7]
Currently, any type of image file is converted to `.png`  during output. The image should inherit the original extension.

**Comment by yasharora102** [comment]
Later a new feature can be made to ask the user to specify the file type.

**Comment by RezaRazmara** [comment]
Hi Yash
in this commit, this code preserves the type extension of the image, i put an cameraman.tif image in the original directory for your tests. in addition to this, the colorzied_image in the static directory will be removed automatically without need to do it handfully. and if the file is not chosen in the webbrowser, it will show a error message for it.
[5363f52](https://github.com/yasharora102/image-colorization-api/pull/8/commits/5363f5209a02c4deada0585e45db20d39dac4c1d)
